package LOGIN;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author julio
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrar = new javax.swing.JLabel();
        olvidocontra = new javax.swing.JLabel();
        ingresar = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        fondo = new javax.swing.JPanel();
        usutxt = new javax.swing.JLabel();
        contratxt = new javax.swing.JLabel();
        fieldusu = new javax.swing.JTextField();
        store = new javax.swing.JLabel();
        crearusu = new javax.swing.JLabel();
        regist = new javax.swing.JLabel();
        olvidocont = new javax.swing.JLabel();
        recup = new javax.swing.JLabel();
        btningre = new javax.swing.JButton();
        olvicontra = new javax.swing.JLabel();
        o = new javax.swing.JLabel();
        gmail = new javax.swing.JLabel();
        faceb = new javax.swing.JLabel();
        logouni = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        registrar.setForeground(new java.awt.Color(0, 153, 255));
        registrar.setText("Registrate");

        olvidocontra.setText("¿Olvido su contraseña?");

        ingresar.setBackground(new java.awt.Color(0, 153, 255));
        ingresar.setForeground(new java.awt.Color(255, 255, 255));
        ingresar.setText("INGRESAR");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        usutxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usutxt.setText("Usuario:");

        contratxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contratxt.setText("Contraseña:");

        fieldusu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldusu.setFocusable(false);
        fieldusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldusuActionPerformed(evt);
            }
        });

        store.setFont(new java.awt.Font("Impact", 0, 26)); // NOI18N
        store.setForeground(new java.awt.Color(255, 204, 51));
        store.setText("STORE");

        crearusu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        crearusu.setText("¿No tienes Usuario? ");

        regist.setBackground(new java.awt.Color(0, 51, 102));
        regist.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        regist.setForeground(new java.awt.Color(0, 51, 153));
        regist.setText("Registrate");

        olvidocont.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        olvidocont.setText("¿Olvidaste tu contraseña?");

        recup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        recup.setForeground(new java.awt.Color(0, 51, 102));
        recup.setText("Recuperala");

        btningre.setBackground(new java.awt.Color(0, 51, 153));
        btningre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btningre.setForeground(new java.awt.Color(255, 204, 0));
        btningre.setText("INGRESAR");
        btningre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51), 2));
        btningre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningreActionPerformed(evt);
            }
        });

        olvicontra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        olvicontra.setText("¿Olvidaste la contraseña?");

        o.setBackground(new java.awt.Color(0, 0, 0));
        o.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        o.setText("O");

        gmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/correo-electronico.png"))); // NOI18N

        faceb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/facebook.png"))); // NOI18N

        logouni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Uninorte.png"))); // NOI18N

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(store, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usutxt)
                            .addComponent(contratxt)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(fieldusu, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(gmail)
                        .addGap(26, 26, 26)
                        .addComponent(faceb))
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(olvicontra)
                        .addGroup(fondoLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(btningre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(212, 212, 212))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(logouni))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(o))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(crearusu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regist))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(olvidocont)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(recup)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(logouni, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(store, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(usutxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldusu, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contratxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(olvicontra)
                .addGap(18, 18, 18)
                .addComponent(btningre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(o)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(faceb)
                    .addComponent(gmail))
                .addGap(27, 27, 27)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearusu)
                    .addComponent(regist))
                .addGap(7, 7, 7)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(olvidocont)
                    .addComponent(recup))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        
    }//GEN-LAST:event_ingresarActionPerformed

    private void btningreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningreActionPerformed

    }//GEN-LAST:event_btningreActionPerformed

    private void fieldusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldusuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

  
        
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btningre;
    private javax.swing.JLabel contratxt;
    private javax.swing.JLabel crearusu;
    private javax.swing.JLabel faceb;
    private javax.swing.JTextField fieldusu;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel gmail;
    private javax.swing.JButton ingresar;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel logouni;
    private javax.swing.JLabel o;
    private javax.swing.JLabel olvicontra;
    private javax.swing.JLabel olvidocont;
    private javax.swing.JLabel olvidocontra;
    private javax.swing.JLabel recup;
    private javax.swing.JLabel regist;
    private javax.swing.JLabel registrar;
    private javax.swing.JLabel store;
    private javax.swing.JLabel usutxt;
    // End of variables declaration//GEN-END:variables
}
